-- MySQL Script generated by MySQL Workbench
-- sáb 30 abr 2022 09:08:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BayerCorp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BayerCorp` ;

-- -----------------------------------------------------
-- Schema BayerCorp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BayerCorp` ;
USE `BayerCorp` ;

-- -----------------------------------------------------
-- Table `BayerCorp`.`Ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BayerCorp`.`Ingreso` ;

CREATE TABLE IF NOT EXISTS `BayerCorp`.`Ingreso` (
  `idIngreso` INT NOT NULL AUTO_INCREMENT,
  `Fecha_y_hora` DATETIME NOT NULL,
  `Comentario` TEXT(100) NULL,
  `idVivienda` INT NOT NULL,
  `idAuto` INT NULL,
  `Placa` VARCHAR(10) NOT NULL,
  `Color` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idIngreso`, `idVivienda`),
  INDEX `fk_Ingreso_Vivienda1_idx` (`idVivienda` ASC) VISIBLE,
  UNIQUE INDEX `idIngreso_UNIQUE` (`idIngreso` ASC) VISIBLE,
  INDEX `fk_Ingreso_Auto1_idx` (`idAuto` ASC) VISIBLE,
  CONSTRAINT `fk_Ingreso_Vivienda1`
    FOREIGN KEY (`idVivienda`)
    REFERENCES `BayerCorp`.`Vivienda` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingreso_Auto1`
    FOREIGN KEY (`idAuto`)
    REFERENCES `BayerCorp`.`Auto` (`idAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayerCorp`.`Vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BayerCorp`.`Vivienda` ;

CREATE TABLE IF NOT EXISTS `BayerCorp`.`Vivienda` (
  `idVivienda` INT NOT NULL,
  PRIMARY KEY (`idVivienda`),
  UNIQUE INDEX `idVivienda_UNIQUE` (`idVivienda` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayerCorp`.`Auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BayerCorp`.`Auto` ;

CREATE TABLE IF NOT EXISTS `BayerCorp`.`Auto` (
  `idAuto` INT NOT NULL,
  `Color` VARCHAR(10) NOT NULL,
  `Tipo_Vehiculo` VARCHAR(8) NULL,
  `Placa` VARCHAR(10) NULL,
  PRIMARY KEY (`idAuto`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC) VISIBLE,
  UNIQUE INDEX `idAuto_UNIQUE` (`idAuto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayerCorp`.`Ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BayerCorp`.`Ingreso` ;

CREATE TABLE IF NOT EXISTS `BayerCorp`.`Ingreso` (
  `idIngreso` INT NOT NULL AUTO_INCREMENT,
  `Fecha_y_hora` DATETIME NOT NULL,
  `Comentario` TEXT(100) NULL,
  `idVivienda` INT NOT NULL,
  `idAuto` INT NULL,
  `Placa` VARCHAR(10) NOT NULL,
  `Color` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idIngreso`, `idVivienda`),
  INDEX `fk_Ingreso_Vivienda1_idx` (`idVivienda` ASC) VISIBLE,
  UNIQUE INDEX `idIngreso_UNIQUE` (`idIngreso` ASC) VISIBLE,
  INDEX `fk_Ingreso_Auto1_idx` (`idAuto` ASC) VISIBLE,
  CONSTRAINT `fk_Ingreso_Vivienda1`
    FOREIGN KEY (`idVivienda`)
    REFERENCES `BayerCorp`.`Vivienda` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingreso_Auto1`
    FOREIGN KEY (`idAuto`)
    REFERENCES `BayerCorp`.`Auto` (`idAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayerCorp`.`Auto_Vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BayerCorp`.`Auto_Vivienda` ;

CREATE TABLE IF NOT EXISTS `BayerCorp`.`Auto_Vivienda` (
  `Auto_idAuto` INT NOT NULL,
  `Vivienda_idVivienda` INT NOT NULL,
  PRIMARY KEY (`Auto_idAuto`, `Vivienda_idVivienda`),
  INDEX `fk_Auto_has_Vivienda_Vivienda1_idx` (`Vivienda_idVivienda` ASC) VISIBLE,
  INDEX `fk_Auto_has_Vivienda_Auto1_idx` (`Auto_idAuto` ASC) VISIBLE,
  CONSTRAINT `fk_Auto_has_Vivienda_Auto1`
    FOREIGN KEY (`Auto_idAuto`)
    REFERENCES `BayerCorp`.`Auto` (`idAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auto_has_Vivienda_Vivienda1`
    FOREIGN KEY (`Vivienda_idVivienda`)
    REFERENCES `BayerCorp`.`Vivienda` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `BayerCorp` ;

-- -----------------------------------------------------
-- Placeholder table for view `BayerCorp`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayerCorp`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `BayerCorp`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BayerCorp`.`view1`;
DROP VIEW IF EXISTS `BayerCorp`.`view1` ;
USE `BayerCorp`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
